namespace KuaiyunClient.Services;

internal static class IsoCountryCatalog
{
    public static IReadOnlyList<IsoCountryEntry> All { get; } =
    [
        new("AD", "AND", "安道尔", "Andorra", ["Principality of Andorra"]),
        new("AE", "ARE", "阿拉伯联合酋长国", "United Arab Emirates", []),
        new("AF", "AFG", "阿富汗", "Afghanistan", ["Islamic Republic of Afghanistan"]),
        new("AG", "ATG", "安提瓜和巴布达", "Antigua and Barbuda", []),
        new("AI", "AIA", "安圭拉", "Anguilla", []),
        new("AL", "ALB", "阿尔巴尼亚", "Albania", ["Republic of Albania"]),
        new("AM", "ARM", "亚美尼亚", "Armenia", ["Republic of Armenia"]),
        new("AO", "AGO", "安哥拉", "Angola", ["Republic of Angola"]),
        new("AQ", "ATA", "南极洲", "Antarctica", []),
        new("AR", "ARG", "阿根廷", "Argentina", ["Argentine Republic"]),
        new("AS", "ASM", "美属萨摩亚", "American Samoa", []),
        new("AT", "AUT", "奥地利", "Austria", ["Republic of Austria"]),
        new("AU", "AUS", "澳大利亚", "Australia", []),
        new("AW", "ABW", "阿鲁巴", "Aruba", []),
        new("AX", "ALA", "奥兰群岛", "Åland Islands", []),
        new("AZ", "AZE", "阿塞拜疆", "Azerbaijan", ["Republic of Azerbaijan"]),
        new("BA", "BIH", "波斯尼亚和黑塞哥维那", "Bosnia and Herzegovina", ["Republic of Bosnia and Herzegovina"]),
        new("BB", "BRB", "巴巴多斯", "Barbados", []),
        new("BD", "BGD", "孟加拉国", "Bangladesh", ["People's Republic of Bangladesh"]),
        new("BE", "BEL", "比利时", "Belgium", ["Kingdom of Belgium"]),
        new("BF", "BFA", "布基纳法索", "Burkina Faso", []),
        new("BG", "BGR", "保加利亚", "Bulgaria", ["Republic of Bulgaria"]),
        new("BH", "BHR", "巴林", "Bahrain", ["Kingdom of Bahrain"]),
        new("BI", "BDI", "布隆迪", "Burundi", ["Republic of Burundi"]),
        new("BJ", "BEN", "贝宁", "Benin", ["Republic of Benin"]),
        new("BL", "BLM", "圣巴泰勒米", "Saint Barthélemy", []),
        new("BM", "BMU", "百慕大", "Bermuda", []),
        new("BN", "BRN", "文莱", "Brunei Darussalam", []),
        new("BO", "BOL", "玻利维亚", "Bolivia, Plurinational State of", ["Plurinational State of Bolivia", "Bolivia"]),
        new("BQ", "BES", "荷属加勒比区", "Bonaire, Sint Eustatius and Saba", []),
        new("BR", "BRA", "巴西", "Brazil", ["Federative Republic of Brazil"]),
        new("BS", "BHS", "巴哈马", "Bahamas", ["Commonwealth of the Bahamas"]),
        new("BT", "BTN", "不丹", "Bhutan", ["Kingdom of Bhutan"]),
        new("BV", "BVT", "布韦岛", "Bouvet Island", []),
        new("BW", "BWA", "博茨瓦纳", "Botswana", ["Republic of Botswana"]),
        new("BY", "BLR", "白俄罗斯", "Belarus", ["Republic of Belarus"]),
        new("BZ", "BLZ", "伯利兹", "Belize", []),
        new("CA", "CAN", "加拿大", "Canada", []),
        new("CC", "CCK", "科科斯（基林）群岛", "Cocos (Keeling) Islands", []),
        new("CD", "COD", "刚果（金）", "Congo, The Democratic Republic of the", ["Democratic Republic of the Congo"]),
        new("CF", "CAF", "中非共和国", "Central African Republic", []),
        new("CG", "COG", "刚果（布）", "Congo", ["Republic of the Congo"]),
        new("CH", "CHE", "瑞士", "Switzerland", ["Swiss Confederation"]),
        new("CI", "CIV", "科特迪瓦", "Côte d'Ivoire", ["Republic of Côte d'Ivoire"]),
        new("CK", "COK", "库克群岛", "Cook Islands", []),
        new("CL", "CHL", "智利", "Chile", ["Republic of Chile"]),
        new("CM", "CMR", "喀麦隆", "Cameroon", ["Republic of Cameroon"]),
        new("CN", "CHN", "中国", "China", ["People's Republic of China"]),
        new("CO", "COL", "哥伦比亚", "Colombia", ["Republic of Colombia"]),
        new("CR", "CRI", "哥斯达黎加", "Costa Rica", ["Republic of Costa Rica"]),
        new("CU", "CUB", "古巴", "Cuba", ["Republic of Cuba"]),
        new("CV", "CPV", "佛得角", "Cabo Verde", ["Republic of Cabo Verde"]),
        new("CW", "CUW", "库拉索", "Curaçao", ["Country of Curaçao"]),
        new("CX", "CXR", "圣诞岛", "Christmas Island", []),
        new("CY", "CYP", "塞浦路斯", "Cyprus", ["Republic of Cyprus"]),
        new("CZ", "CZE", "捷克", "Czechia", ["Czech Republic"]),
        new("DE", "DEU", "德国", "Germany", ["Federal Republic of Germany"]),
        new("DJ", "DJI", "吉布提", "Djibouti", ["Republic of Djibouti"]),
        new("DK", "DNK", "丹麦", "Denmark", ["Kingdom of Denmark"]),
        new("DM", "DMA", "多米尼克", "Dominica", ["Commonwealth of Dominica"]),
        new("DO", "DOM", "多米尼加共和国", "Dominican Republic", []),
        new("DZ", "DZA", "阿尔及利亚", "Algeria", ["People's Democratic Republic of Algeria"]),
        new("EC", "ECU", "厄瓜多尔", "Ecuador", ["Republic of Ecuador"]),
        new("EE", "EST", "爱沙尼亚", "Estonia", ["Republic of Estonia"]),
        new("EG", "EGY", "埃及", "Egypt", ["Arab Republic of Egypt"]),
        new("EH", "ESH", "西撒哈拉", "Western Sahara", []),
        new("ER", "ERI", "厄立特里亚", "Eritrea", ["the State of Eritrea"]),
        new("ES", "ESP", "西班牙", "Spain", ["Kingdom of Spain"]),
        new("ET", "ETH", "埃塞俄比亚", "Ethiopia", ["Federal Democratic Republic of Ethiopia"]),
        new("FI", "FIN", "芬兰", "Finland", ["Republic of Finland"]),
        new("FJ", "FJI", "斐济", "Fiji", ["Republic of Fiji"]),
        new("FK", "FLK", "福克兰群岛", "Falkland Islands (Malvinas)", []),
        new("FM", "FSM", "密克罗尼西亚", "Micronesia, Federated States of", ["Federated States of Micronesia", "Micronesia"]),
        new("FO", "FRO", "法罗群岛", "Faroe Islands", []),
        new("FR", "FRA", "法国", "France", ["French Republic"]),
        new("GA", "GAB", "加蓬", "Gabon", ["Gabonese Republic"]),
        new("GB", "GBR", "英国", "United Kingdom", ["United Kingdom of Great Britain and Northern Ireland"]),
        new("GD", "GRD", "格林纳达", "Grenada", []),
        new("GE", "GEO", "格鲁吉亚", "Georgia", []),
        new("GF", "GUF", "法属圭亚那", "French Guiana", []),
        new("GG", "GGY", "根西岛", "Guernsey", []),
        new("GH", "GHA", "加纳", "Ghana", ["Republic of Ghana"]),
        new("GI", "GIB", "直布罗陀", "Gibraltar", []),
        new("GL", "GRL", "格陵兰", "Greenland", []),
        new("GM", "GMB", "冈比亚", "Gambia", ["Republic of the Gambia"]),
        new("GN", "GIN", "几内亚", "Guinea", ["Republic of Guinea"]),
        new("GP", "GLP", "瓜德罗普", "Guadeloupe", []),
        new("GQ", "GNQ", "赤道几内亚", "Equatorial Guinea", ["Republic of Equatorial Guinea"]),
        new("GR", "GRC", "希腊", "Greece", ["Hellenic Republic"]),
        new("GS", "SGS", "南乔治亚和南桑威奇群岛", "South Georgia and the South Sandwich Islands", []),
        new("GT", "GTM", "危地马拉", "Guatemala", ["Republic of Guatemala"]),
        new("GU", "GUM", "关岛", "Guam", []),
        new("GW", "GNB", "几内亚比绍", "Guinea-Bissau", ["Republic of Guinea-Bissau"]),
        new("GY", "GUY", "圭亚那", "Guyana", ["Republic of Guyana"]),
        new("HK", "HKG", "香港", "Hong Kong", ["Hong Kong Special Administrative Region of China"]),
        new("HM", "HMD", "赫德岛和麦克唐纳群岛", "Heard Island and McDonald Islands", []),
        new("HN", "HND", "洪都拉斯", "Honduras", ["Republic of Honduras"]),
        new("HR", "HRV", "克罗地亚", "Croatia", ["Republic of Croatia"]),
        new("HT", "HTI", "海地", "Haiti", ["Republic of Haiti"]),
        new("HU", "HUN", "匈牙利", "Hungary", []),
        new("ID", "IDN", "印度尼西亚", "Indonesia", ["Republic of Indonesia"]),
        new("IE", "IRL", "爱尔兰", "Ireland", []),
        new("IL", "ISR", "以色列", "Israel", ["State of Israel"]),
        new("IM", "IMN", "马恩岛", "Isle of Man", []),
        new("IN", "IND", "印度", "India", ["Republic of India"]),
        new("IO", "IOT", "英属印度洋领地", "British Indian Ocean Territory", []),
        new("IQ", "IRQ", "伊拉克", "Iraq", ["Republic of Iraq"]),
        new("IR", "IRN", "伊朗", "Iran, Islamic Republic of", ["Islamic Republic of Iran", "Iran"]),
        new("IS", "ISL", "冰岛", "Iceland", ["Republic of Iceland"]),
        new("IT", "ITA", "意大利", "Italy", ["Italian Republic"]),
        new("JE", "JEY", "泽西岛", "Jersey", []),
        new("JM", "JAM", "牙买加", "Jamaica", []),
        new("JO", "JOR", "约旦", "Jordan", ["Hashemite Kingdom of Jordan"]),
        new("JP", "JPN", "日本", "Japan", []),
        new("KE", "KEN", "肯尼亚", "Kenya", ["Republic of Kenya"]),
        new("KG", "KGZ", "吉尔吉斯斯坦", "Kyrgyzstan", ["Kyrgyz Republic"]),
        new("KH", "KHM", "柬埔寨", "Cambodia", ["Kingdom of Cambodia"]),
        new("KI", "KIR", "基里巴斯", "Kiribati", ["Republic of Kiribati"]),
        new("KM", "COM", "科摩罗", "Comoros", ["Union of the Comoros"]),
        new("KN", "KNA", "圣基茨和尼维斯", "Saint Kitts and Nevis", []),
        new("KP", "PRK", "朝鲜", "Korea, Democratic People's Republic of", ["Democratic People's Republic of Korea", "North Korea"]),
        new("KR", "KOR", "韩国", "Korea, Republic of", ["Republic of Korea", "South Korea"]),
        new("KW", "KWT", "科威特", "Kuwait", ["State of Kuwait"]),
        new("KY", "CYM", "开曼群岛", "Cayman Islands", []),
        new("KZ", "KAZ", "哈萨克斯坦", "Kazakhstan", ["Republic of Kazakhstan"]),
        new("LA", "LAO", "老挝", "Lao People's Democratic Republic", ["Laos"]),
        new("LB", "LBN", "黎巴嫩", "Lebanon", ["Lebanese Republic"]),
        new("LC", "LCA", "圣卢西亚", "Saint Lucia", []),
        new("LI", "LIE", "列支敦士登", "Liechtenstein", ["Principality of Liechtenstein"]),
        new("LK", "LKA", "斯里兰卡", "Sri Lanka", ["Democratic Socialist Republic of Sri Lanka"]),
        new("LR", "LBR", "利比里亚", "Liberia", ["Republic of Liberia"]),
        new("LS", "LSO", "莱索托", "Lesotho", ["Kingdom of Lesotho"]),
        new("LT", "LTU", "立陶宛", "Lithuania", ["Republic of Lithuania"]),
        new("LU", "LUX", "卢森堡", "Luxembourg", ["Grand Duchy of Luxembourg"]),
        new("LV", "LVA", "拉脱维亚", "Latvia", ["Republic of Latvia"]),
        new("LY", "LBY", "利比亚", "Libya", ["State of Libya"]),
        new("MA", "MAR", "摩洛哥", "Morocco", ["Kingdom of Morocco"]),
        new("MC", "MCO", "摩纳哥", "Monaco", ["Principality of Monaco"]),
        new("MD", "MDA", "摩尔多瓦", "Moldova, Republic of", ["Republic of Moldova", "Moldova"]),
        new("ME", "MNE", "黑山", "Montenegro", []),
        new("MF", "MAF", "法属圣马丁", "Saint Martin (French part)", []),
        new("MG", "MDG", "马达加斯加", "Madagascar", ["Republic of Madagascar"]),
        new("MH", "MHL", "马绍尔群岛", "Marshall Islands", ["Republic of the Marshall Islands"]),
        new("MK", "MKD", "北马其顿", "North Macedonia", ["Republic of North Macedonia"]),
        new("ML", "MLI", "马里", "Mali", ["Republic of Mali"]),
        new("MM", "MMR", "缅甸", "Myanmar", ["Republic of Myanmar", "Burma"]),
        new("MN", "MNG", "蒙古", "Mongolia", []),
        new("MO", "MAC", "澳门", "Macao", ["Macao Special Administrative Region of China"]),
        new("MP", "MNP", "北马里亚纳群岛", "Northern Mariana Islands", ["Commonwealth of the Northern Mariana Islands"]),
        new("MQ", "MTQ", "马提尼克", "Martinique", []),
        new("MR", "MRT", "毛里塔尼亚", "Mauritania", ["Islamic Republic of Mauritania"]),
        new("MS", "MSR", "蒙特塞拉特", "Montserrat", []),
        new("MT", "MLT", "马耳他", "Malta", ["Republic of Malta"]),
        new("MU", "MUS", "毛里求斯", "Mauritius", ["Republic of Mauritius"]),
        new("MV", "MDV", "马尔代夫", "Maldives", ["Republic of Maldives"]),
        new("MW", "MWI", "马拉维", "Malawi", ["Republic of Malawi"]),
        new("MX", "MEX", "墨西哥", "Mexico", ["United Mexican States"]),
        new("MY", "MYS", "马来西亚", "Malaysia", []),
        new("MZ", "MOZ", "莫桑比克", "Mozambique", ["Republic of Mozambique"]),
        new("NA", "NAM", "纳米比亚", "Namibia", ["Republic of Namibia"]),
        new("NC", "NCL", "新喀里多尼亚", "New Caledonia", []),
        new("NE", "NER", "尼日尔", "Niger", ["Republic of the Niger"]),
        new("NF", "NFK", "诺福克岛", "Norfolk Island", []),
        new("NG", "NGA", "尼日利亚", "Nigeria", ["Federal Republic of Nigeria"]),
        new("NI", "NIC", "尼加拉瓜", "Nicaragua", ["Republic of Nicaragua"]),
        new("NL", "NLD", "荷兰", "Netherlands", ["Kingdom of the Netherlands"]),
        new("NO", "NOR", "挪威", "Norway", ["Kingdom of Norway"]),
        new("NP", "NPL", "尼泊尔", "Nepal", ["Federal Democratic Republic of Nepal"]),
        new("NR", "NRU", "瑙鲁", "Nauru", ["Republic of Nauru"]),
        new("NU", "NIU", "纽埃", "Niue", []),
        new("NZ", "NZL", "新西兰", "New Zealand", []),
        new("OM", "OMN", "阿曼", "Oman", ["Sultanate of Oman"]),
        new("PA", "PAN", "巴拿马", "Panama", ["Republic of Panama"]),
        new("PE", "PER", "秘鲁", "Peru", ["Republic of Peru"]),
        new("PF", "PYF", "法属波利尼西亚", "French Polynesia", []),
        new("PG", "PNG", "巴布亚新几内亚", "Papua New Guinea", ["Independent State of Papua New Guinea"]),
        new("PH", "PHL", "菲律宾", "Philippines", ["Republic of the Philippines"]),
        new("PK", "PAK", "巴基斯坦", "Pakistan", ["Islamic Republic of Pakistan"]),
        new("PL", "POL", "波兰", "Poland", ["Republic of Poland"]),
        new("PM", "SPM", "圣皮埃尔和密克隆群岛", "Saint Pierre and Miquelon", []),
        new("PN", "PCN", "皮特凯恩群岛", "Pitcairn", []),
        new("PR", "PRI", "波多黎各", "Puerto Rico", []),
        new("PS", "PSE", "巴勒斯坦", "Palestine, State of", ["the State of Palestine", "Palestine"]),
        new("PT", "PRT", "葡萄牙", "Portugal", ["Portuguese Republic"]),
        new("PW", "PLW", "帕劳", "Palau", ["Republic of Palau"]),
        new("PY", "PRY", "巴拉圭", "Paraguay", ["Republic of Paraguay"]),
        new("QA", "QAT", "卡塔尔", "Qatar", ["State of Qatar"]),
        new("RE", "REU", "留尼汪", "Réunion", []),
        new("RO", "ROU", "罗马尼亚", "Romania", []),
        new("RS", "SRB", "塞尔维亚", "Serbia", ["Republic of Serbia"]),
        new("RU", "RUS", "俄罗斯", "Russian Federation", ["Russia"]),
        new("RW", "RWA", "卢旺达", "Rwanda", ["Republic of Rwanda"]),
        new("SA", "SAU", "沙特阿拉伯", "Saudi Arabia", ["Kingdom of Saudi Arabia"]),
        new("SB", "SLB", "所罗门群岛", "Solomon Islands", []),
        new("SC", "SYC", "塞舌尔", "Seychelles", ["Republic of Seychelles"]),
        new("SD", "SDN", "苏丹", "Sudan", ["Republic of the Sudan"]),
        new("SE", "SWE", "瑞典", "Sweden", ["Kingdom of Sweden"]),
        new("SG", "SGP", "新加坡", "Singapore", ["Republic of Singapore"]),
        new("SH", "SHN", "圣赫勒拿、阿森松和特里斯坦-达库尼亚", "Saint Helena, Ascension and Tristan da Cunha", []),
        new("SI", "SVN", "斯洛文尼亚", "Slovenia", ["Republic of Slovenia"]),
        new("SJ", "SJM", "斯瓦尔巴和扬马延", "Svalbard and Jan Mayen", []),
        new("SK", "SVK", "斯洛伐克", "Slovakia", ["Slovak Republic"]),
        new("SL", "SLE", "塞拉利昂", "Sierra Leone", ["Republic of Sierra Leone"]),
        new("SM", "SMR", "圣马力诺", "San Marino", ["Republic of San Marino"]),
        new("SN", "SEN", "塞内加尔", "Senegal", ["Republic of Senegal"]),
        new("SO", "SOM", "索马里", "Somalia", ["Federal Republic of Somalia"]),
        new("SR", "SUR", "苏里南", "Suriname", ["Republic of Suriname"]),
        new("SS", "SSD", "南苏丹", "South Sudan", ["Republic of South Sudan"]),
        new("ST", "STP", "圣多美和普林西比", "Sao Tome and Principe", ["Democratic Republic of Sao Tome and Principe"]),
        new("SV", "SLV", "萨尔瓦多", "El Salvador", ["Republic of El Salvador"]),
        new("SX", "SXM", "荷属圣马丁", "Sint Maarten (Dutch part)", []),
        new("SY", "SYR", "叙利亚", "Syrian Arab Republic", ["Syria"]),
        new("SZ", "SWZ", "斯威士兰", "Eswatini", ["Kingdom of Eswatini", "Swaziland"]),
        new("TC", "TCA", "特克斯和凯科斯群岛", "Turks and Caicos Islands", []),
        new("TD", "TCD", "乍得", "Chad", ["Republic of Chad"]),
        new("TF", "ATF", "法属南部领地", "French Southern Territories", []),
        new("TG", "TGO", "多哥", "Togo", ["Togolese Republic"]),
        new("TH", "THA", "泰国", "Thailand", ["Kingdom of Thailand"]),
        new("TJ", "TJK", "塔吉克斯坦", "Tajikistan", ["Republic of Tajikistan"]),
        new("TK", "TKL", "托克劳", "Tokelau", []),
        new("TL", "TLS", "东帝汶", "Timor-Leste", ["Democratic Republic of Timor-Leste"]),
        new("TM", "TKM", "土库曼斯坦", "Turkmenistan", []),
        new("TN", "TUN", "突尼斯", "Tunisia", ["Republic of Tunisia"]),
        new("TO", "TON", "汤加", "Tonga", ["Kingdom of Tonga"]),
        new("TR", "TUR", "土耳其", "Türkiye", ["Republic of Türkiye", "Turkey"]),
        new("TT", "TTO", "特立尼达和多巴哥", "Trinidad and Tobago", ["Republic of Trinidad and Tobago"]),
        new("TV", "TUV", "图瓦卢", "Tuvalu", []),
        new("TW", "TWN", "台湾", "Taiwan, Province of China", ["Taiwan"]),
        new("TZ", "TZA", "坦桑尼亚", "Tanzania, United Republic of", ["United Republic of Tanzania", "Tanzania"]),
        new("UA", "UKR", "乌克兰", "Ukraine", []),
        new("UG", "UGA", "乌干达", "Uganda", ["Republic of Uganda"]),
        new("UM", "UMI", "美国本土外小岛屿", "United States Minor Outlying Islands", []),
        new("US", "USA", "美国", "United States", ["United States of America"]),
        new("UY", "URY", "乌拉圭", "Uruguay", ["Oriental Republic of Uruguay"]),
        new("UZ", "UZB", "乌兹别克斯坦", "Uzbekistan", ["Republic of Uzbekistan"]),
        new("VA", "VAT", "梵蒂冈", "Holy See (Vatican City State)", []),
        new("VC", "VCT", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", []),
        new("VE", "VEN", "委内瑞拉", "Venezuela, Bolivarian Republic of", ["Bolivarian Republic of Venezuela", "Venezuela"]),
        new("VG", "VGB", "英属维尔京群岛", "Virgin Islands, British", ["British Virgin Islands"]),
        new("VI", "VIR", "美属维尔京群岛", "Virgin Islands, U.S.", ["Virgin Islands of the United States"]),
        new("VN", "VNM", "越南", "Viet Nam", ["Socialist Republic of Viet Nam", "Vietnam"]),
        new("VU", "VUT", "瓦努阿图", "Vanuatu", ["Republic of Vanuatu"]),
        new("WF", "WLF", "瓦利斯和富图纳", "Wallis and Futuna", []),
        new("WS", "WSM", "萨摩亚", "Samoa", ["Independent State of Samoa"]),
        new("YE", "YEM", "也门", "Yemen", ["Republic of Yemen"]),
        new("YT", "MYT", "马约特", "Mayotte", []),
        new("ZA", "ZAF", "南非", "South Africa", ["Republic of South Africa"]),
        new("ZM", "ZMB", "赞比亚", "Zambia", ["Republic of Zambia"]),
        new("ZW", "ZWE", "津巴布韦", "Zimbabwe", ["Republic of Zimbabwe"]),
        new("EU", "EUR", "欧盟", "European Union", ["EU", "Europe"]),
        new("UN", "UNO", "联合国", "United Nations", ["UN"]),
        new("XK", "XKS", "科索沃", "Kosovo", ["Kosova"]),
    ];
}

internal sealed record IsoCountryEntry(
    string Alpha2,
    string Alpha3,
    string ChineseName,
    string EnglishName,
    string[] AlternateNames);
